services:
  paperless-postgres-db:
    image: docker.io/library/postgres:17
    container_name: paperless-postgres-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - paperless-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD_FILE=/run/secrets/paperless_pg_paperless_password
      - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/paperless_pg_postgres_password
    secrets:
      - paperless_pg_paperless_password
      - paperless_pg_postgres_password

  paperless-redis:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    restart: unless-stopped
#    ports:
#      - "6380:6379"
    volumes:
      - paperless-redisdata:/data

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_DBHOST=paperless-postgres-db
      - PAPERLESS_DBPORT=5433
      - PAPERLESS_OCR_LANGUAGE=deu+eng
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - USERMAP_GID=1001
      - USERMAP_UID=1000
    depends_on:
      - paperless-postgres-db
      - paperless-redis

volumes:
  paperless-data:
  paperless-media:
  paperless-pgdata:
  paperless-redisdata:

secrets:
  paperless_pg_paperless_password:
    file: ./secrets/paperless_pg_paperless.txt
  paperless_pg_postgres_password:
    file: ./secrets/paperless_pg_postgres.txt

